### ISSUE TITLE
linker cc not found

### ISSUE THREAD

**Issue by maxx6262** [dacadeorg/ICP-azle-boilerplate#4]
**As i get error 101 during message_board compilation, I've finally found that command**
```
npx azle message_board -v
``` 
was getting 101 compilation error due to cc linker missing 
<details>Configuration</summary>
<p>
EC2 instance on GCloud 
Ubuntu 20.04.6
node 18 through nvm
dfx 0.14
</p>
</details> 

I finally succesfully built cannister by installing ** gcc **
```
sudo apt install gcc
``` 

You can add this on Dacade tutorial page :)

**Comment by nathaniawong** [comment]
Thanks for your PR! However, this is an env specific issue and we cannot cover all of them, so I will close this issue.

**Comment by nathaniawong** [comment]
Thanks for your PR! However, this is an env specific issue and we cannot cover all of them, so I will close this issue.
